CREATE TABLE ClassEquipment (quantity INTEGER, classId BIGINT NOT NULL, equipmentId BIGINT NOT NULL, PRIMARY KEY (classId, equipmentId))
CREATE TABLE Deity (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, shortDescription VARCHAR(255), description TEXT, alignmentId BIGINT, symbol VARCHAR(255), image LONGBLOB, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Equipment (id BIGINT AUTO_INCREMENT NOT NULL, type VARCHAR(31), name VARCHAR(255) NOT NULL UNIQUE, description TEXT, weight DOUBLE NOT NULL, isMagical TINYINT(1) default 0 NOT NULL, isPurchasable TINYINT(1) default 0 NOT NULL, isSellable TINYINT(1) default 0 NOT NULL, basePrice INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Tool (id BIGINT NOT NULL, toolType VARCHAR(255) NOT NULL, PRIMARY KEY (id))
CREATE TABLE Class (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, shortDescription VARCHAR(255), description TEXT, lifePointPerLevel INTEGER NOT NULL, isSpellCasting TINYINT(1) default 0, spellCasingAbilityId BIGINT, nbChosenSkills INTEGER, startingGold INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Ability (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, abbreviation VARCHAR(3), version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE City (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, shortDescription VARCHAR(255), description TEXT, regionId BIGINT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE ClassSpecLevelFeature (classSpecId BIGINT NOT NULL, featId BIGINT NOT NULL, levelId BIGINT NOT NULL, PRIMARY KEY (classSpecId, featId, levelId))
CREATE TABLE ClassSpecialization (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, classId BIGINT NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Alignment (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) UNIQUE, abbreviation VARCHAR(2) UNIQUE, shortDescription VARCHAR(255), description TEXT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE ClassLevelBonusFeat (classId BIGINT NOT NULL, featId BIGINT NOT NULL, levelId BIGINT NOT NULL, PRIMARY KEY (classId, featId, levelId))
CREATE TABLE CharacterClass (classLevel INTEGER, characterId BIGINT NOT NULL, classId BIGINT NOT NULL, PRIMARY KEY (characterId, classId))
CREATE TABLE DivineDomainSpell (level INTEGER, domainId BIGINT NOT NULL, spellId BIGINT NOT NULL, PRIMARY KEY (domainId, spellId))
CREATE TABLE ArmorType (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, proficiencyType VARCHAR(255) NOT NULL, maxDexBonus INTEGER NOT NULL, baseArmorClass INTEGER NOT NULL, stealthDisavantage TINYINT(1) default 0 NOT NULL, minStrength INTEGER NOT NULL, baseWeight DOUBLE NOT NULL, basePrice INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE DamageType (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description VARCHAR(255), version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE ClassLevelBonus (chooseClassSpecialization TINYINT(1) default 0, abilityScoreImprovement TINYINT(1) default 0, spellBonus INTEGER, spellPerDay0 INTEGER, spellPerDay1 INTEGER, spellPerDay2 INTEGER, spellPerDay3 INTEGER, spellPerDay4 INTEGER, spellPerDay5 INTEGER, spellPerDay6 INTEGER, spellPerDay7 INTEGER, spellPerDay8 INTEGER, spellPerDay9 INTEGER, classId BIGINT NOT NULL, levelId BIGINT NOT NULL, PRIMARY KEY (classId, levelId))
CREATE TABLE DivineDomain (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Feat (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, featUsage VARCHAR(255) NOT NULL, isClassFeature TINYINT(1) default 0, prerequisiteType VARCHAR(255) NOT NULL, prerequisiteArmorProficiency VARCHAR(255), prerequisiteAbilityId BIGINT, prerequisiteAbilityScore INTEGER, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE ClassSkill (classId BIGINT NOT NULL, skillId BIGINT NOT NULL, PRIMARY KEY (classId, skillId))
CREATE TABLE Region (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE CharacterEquipment (quantity INTEGER, sellableValue DECIMAL(38), characterId BIGINT NOT NULL, equipmentId BIGINT NOT NULL, PRIMARY KEY (characterId, equipmentId))
CREATE TABLE Background (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, traits TEXT, ideals TEXT, purposes TEXT, flaws TEXT, additionalLanguage INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Shop (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, cityId BIGINT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE WeaponType (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, proficiencyType VARCHAR(255) NOT NULL, sizeType VARCHAR(255) NOT NULL, handleType VARCHAR(255) NOT NULL, usageType VARCHAR(255) NOT NULL, rangeType VARCHAR(255), oneHandBaseDamage VARCHAR(255), twoHandBaseDamage VARCHAR(255), damageTypeId BIGINT NOT NULL, isReach TINYINT(1) default 0, isFinesse TINYINT(1) default 0, isLoading TINYINT(1) default 0, baseWeight DOUBLE, basePrice INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Level (id BIGINT NOT NULL, maxExperience BIGINT, proficiencyBonus INTEGER, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Spell (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, level INTEGER NOT NULL, school VARCHAR(255) NOT NULL, castingTime VARCHAR(255) NOT NULL, castingTimeValue INTEGER, castingTimeUnit VARCHAR(255), duration VARCHAR(255) NOT NULL, durationTimeValue INTEGER, durationTimeUnit VARCHAR(255), target VARCHAR(255) NOT NULL, areaOfEffect VARCHAR(255), rangeType VARCHAR(255) NOT NULL, rangeValueInFeet INTEGER, savingThrowAbilityId BIGINT, attackRoll TINYINT(1) default 0, higherLevel TINYINT(1) default 0, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Language (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, script VARCHAR(255), version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Race (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, traits TEXT, strModifier INTEGER, dexModifier INTEGER, conModifier INTEGER, intModifier INTEGER, wisModifier INTEGER, chaModifier INTEGER, minAge INTEGER, maxAge INTEGER, size VARCHAR(255) NOT NULL, averageHeight VARCHAR(255), averageWeight INTEGER, speed INTEGER, extraLanguage TINYINT(1) default 0, damageTypeId BIGINT, image LONGBLOB, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE SpellEffect (id BIGINT AUTO_INCREMENT NOT NULL, effectType VARCHAR(255) NOT NULL, damage VARCHAR(255), damageTypeId BIGINT, armorClass INTEGER, conditionName VARCHAR(255), spellId BIGINT NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Weapon (id BIGINT NOT NULL, additionalDamage VARCHAR(255), magicalBonus INTEGER, oneHandDamage VARCHAR(255), twoHandDamage VARCHAR(255), additionalDamageTypeId BIGINT, weaponTypeId BIGINT, PRIMARY KEY (id))
CREATE TABLE ShopEquipment (quantity INTEGER, unitPrice INTEGER, equipmentId BIGINT NOT NULL, shopId BIGINT NOT NULL, PRIMARY KEY (equipmentId, shopId))
CREATE TABLE Armor (id BIGINT NOT NULL, armorClass INTEGER, magicalAcBonus INTEGER, armorTypeId BIGINT, PRIMARY KEY (id))
CREATE TABLE Adventure (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT, creatorId BIGINT, status VARCHAR(255) NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE DSCharacter (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, gender CHAR(1) NOT NULL, age INTEGER NOT NULL, weight INTEGER NOT NULL, heigth INTEGER NOT NULL, raceId BIGINT NOT NULL, levelId BIGINT NOT NULL, experience BIGINT NOT NULL, lifePoints INTEGER NOT NULL, baseArmorClass INTEGER NOT NULL, background TEXT, look TEXT, personnality TEXT, alignmentId BIGINT NOT NULL, regionId BIGINT NOT NULL, adventureId BIGINT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE AccessRole (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, roleType INTEGER NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE User (id BIGINT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, roleId BIGINT, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, status INTEGER NOT NULL, characterId BIGINT, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Skill (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL UNIQUE, shortDescription VARCHAR(255), description TEXT, keyAbilityId BIGINT NOT NULL, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE Message (id BIGINT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, text TEXT, adventureId BIGINT, characterId BIGINT, isXpGiven TINYINT(1) default 0, version INTEGER, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id))
CREATE TABLE DeityDomain (deityId BIGINT NOT NULL, domainId BIGINT NOT NULL, PRIMARY KEY (deityId, domainId))
CREATE TABLE ClassSavingThrowProficiencies (classId BIGINT NOT NULL, abilityId BIGINT NOT NULL, PRIMARY KEY (classId, abilityId))
CREATE TABLE ClassArmorProficiencies (classId BIGINT NOT NULL, proficiency VARCHAR(255) NOT NULL)
CREATE TABLE ClassWeaponProficiencies (classId BIGINT NOT NULL, weaponTypeId BIGINT NOT NULL, PRIMARY KEY (classId, weaponTypeId))
CREATE TABLE ClassSpell (classId BIGINT NOT NULL, spellId BIGINT NOT NULL, PRIMARY KEY (classId, spellId))
CREATE TABLE CharacterFeat (featId BIGINT NOT NULL, characterId BIGINT NOT NULL, PRIMARY KEY (featId, characterId))
CREATE TABLE BackgroundSkillProficiencies (backgroundId BIGINT NOT NULL, skillId BIGINT NOT NULL, PRIMARY KEY (backgroundId, skillId))
CREATE TABLE BackgroundToolProficiencies (backgroundId BIGINT NOT NULL, toolType VARCHAR(255) NOT NULL)
CREATE TABLE SpellComponentType (spellId BIGINT NOT NULL, componentType VARCHAR(255) NOT NULL)
CREATE TABLE SpellComponent (spellId BIGINT NOT NULL, equipmentId BIGINT NOT NULL, PRIMARY KEY (spellId, equipmentId))
CREATE TABLE RaceLanguage (raceId BIGINT NOT NULL, languageId BIGINT NOT NULL, PRIMARY KEY (raceId, languageId))
CREATE TABLE RaceSavingThrowProficiencies (raceId BIGINT NOT NULL, conditionName VARCHAR(255) NOT NULL)
CREATE TABLE RaceArmorProficiencies (raceId BIGINT NOT NULL, proficiency VARCHAR(255) NOT NULL)
CREATE TABLE RaceWeaponProficiencies (raceId BIGINT NOT NULL, weaponTypeId BIGINT NOT NULL, PRIMARY KEY (raceId, weaponTypeId))
CREATE TABLE RaceSkillProficiencies (raceId BIGINT NOT NULL, skillId BIGINT NOT NULL, PRIMARY KEY (raceId, skillId))
CREATE TABLE CharacterProficientSkill (characterId BIGINT NOT NULL, skillId BIGINT NOT NULL, PRIMARY KEY (characterId, skillId))
ALTER TABLE ClassEquipment ADD CONSTRAINT FK_ClassEquipment_equipmentId FOREIGN KEY (equipmentId) REFERENCES Equipment (id)
ALTER TABLE ClassEquipment ADD CONSTRAINT FK_ClassEquipment_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE Deity ADD CONSTRAINT FK_Deity_alignmentId FOREIGN KEY (alignmentId) REFERENCES Alignment (id)
ALTER TABLE Tool ADD CONSTRAINT FK_Tool_id FOREIGN KEY (id) REFERENCES Equipment (id)
ALTER TABLE Class ADD CONSTRAINT FK_Class_spellCasingAbilityId FOREIGN KEY (spellCasingAbilityId) REFERENCES Ability (id)
ALTER TABLE City ADD CONSTRAINT FK_City_regionId FOREIGN KEY (regionId) REFERENCES Region (id)
ALTER TABLE ClassSpecLevelFeature ADD CONSTRAINT FK_ClassSpecLevelFeature_classSpecId FOREIGN KEY (classSpecId) REFERENCES ClassSpecialization (id)
ALTER TABLE ClassSpecLevelFeature ADD CONSTRAINT FK_ClassSpecLevelFeature_levelId FOREIGN KEY (levelId) REFERENCES Level (id)
ALTER TABLE ClassSpecLevelFeature ADD CONSTRAINT FK_ClassSpecLevelFeature_featId FOREIGN KEY (featId) REFERENCES Feat (id)
ALTER TABLE ClassSpecialization ADD CONSTRAINT FK_ClassSpecialization_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassLevelBonusFeat ADD CONSTRAINT FK_ClassLevelBonusFeat_levelId FOREIGN KEY (levelId) REFERENCES Level (id)
ALTER TABLE ClassLevelBonusFeat ADD CONSTRAINT FK_ClassLevelBonusFeat_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassLevelBonusFeat ADD CONSTRAINT FK_ClassLevelBonusFeat_featId FOREIGN KEY (featId) REFERENCES Feat (id)
ALTER TABLE CharacterClass ADD CONSTRAINT FK_CharacterClass_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE CharacterClass ADD CONSTRAINT FK_CharacterClass_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE DivineDomainSpell ADD CONSTRAINT FK_DivineDomainSpell_spellId FOREIGN KEY (spellId) REFERENCES Spell (id)
ALTER TABLE DivineDomainSpell ADD CONSTRAINT FK_DivineDomainSpell_domainId FOREIGN KEY (domainId) REFERENCES DivineDomain (id)
ALTER TABLE ClassLevelBonus ADD CONSTRAINT FK_ClassLevelBonus_levelId FOREIGN KEY (levelId) REFERENCES Level (id)
ALTER TABLE ClassLevelBonus ADD CONSTRAINT FK_ClassLevelBonus_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE Feat ADD CONSTRAINT FK_Feat_prerequisiteAbilityId FOREIGN KEY (prerequisiteAbilityId) REFERENCES Ability (id)
ALTER TABLE ClassSkill ADD CONSTRAINT FK_ClassSkill_skillId FOREIGN KEY (skillId) REFERENCES Skill (id)
ALTER TABLE ClassSkill ADD CONSTRAINT FK_ClassSkill_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE CharacterEquipment ADD CONSTRAINT FK_CharacterEquipment_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE CharacterEquipment ADD CONSTRAINT FK_CharacterEquipment_equipmentId FOREIGN KEY (equipmentId) REFERENCES Equipment (id)
ALTER TABLE Shop ADD CONSTRAINT FK_Shop_cityId FOREIGN KEY (cityId) REFERENCES City (id)
ALTER TABLE WeaponType ADD CONSTRAINT FK_WeaponType_damageTypeId FOREIGN KEY (damageTypeId) REFERENCES DamageType (id)
ALTER TABLE Spell ADD CONSTRAINT FK_Spell_savingThrowAbilityId FOREIGN KEY (savingThrowAbilityId) REFERENCES Ability (id)
ALTER TABLE Race ADD CONSTRAINT FK_Race_damageTypeId FOREIGN KEY (damageTypeId) REFERENCES DamageType (id)
ALTER TABLE SpellEffect ADD CONSTRAINT FK_SpellEffect_spellId FOREIGN KEY (spellId) REFERENCES Spell (id)
ALTER TABLE SpellEffect ADD CONSTRAINT FK_SpellEffect_damageTypeId FOREIGN KEY (damageTypeId) REFERENCES DamageType (id)
ALTER TABLE Weapon ADD CONSTRAINT FK_Weapon_additionalDamageTypeId FOREIGN KEY (additionalDamageTypeId) REFERENCES DamageType (id)
ALTER TABLE Weapon ADD CONSTRAINT FK_Weapon_weaponTypeId FOREIGN KEY (weaponTypeId) REFERENCES WeaponType (id)
ALTER TABLE Weapon ADD CONSTRAINT FK_Weapon_id FOREIGN KEY (id) REFERENCES Equipment (id)
ALTER TABLE ShopEquipment ADD CONSTRAINT FK_ShopEquipment_shopId FOREIGN KEY (shopId) REFERENCES Shop (id)
ALTER TABLE ShopEquipment ADD CONSTRAINT FK_ShopEquipment_equipmentId FOREIGN KEY (equipmentId) REFERENCES Equipment (id)
ALTER TABLE Armor ADD CONSTRAINT FK_Armor_id FOREIGN KEY (id) REFERENCES Equipment (id)
ALTER TABLE Armor ADD CONSTRAINT FK_Armor_armorTypeId FOREIGN KEY (armorTypeId) REFERENCES ArmorType (id)
ALTER TABLE Adventure ADD CONSTRAINT FK_Adventure_creatorId FOREIGN KEY (creatorId) REFERENCES User (id)
ALTER TABLE DSCharacter ADD CONSTRAINT FK_DSCharacter_levelId FOREIGN KEY (levelId) REFERENCES Level (id)
ALTER TABLE DSCharacter ADD CONSTRAINT FK_DSCharacter_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE DSCharacter ADD CONSTRAINT FK_DSCharacter_regionId FOREIGN KEY (regionId) REFERENCES Region (id)
ALTER TABLE DSCharacter ADD CONSTRAINT FK_DSCharacter_alignmentId FOREIGN KEY (alignmentId) REFERENCES Alignment (id)
ALTER TABLE DSCharacter ADD CONSTRAINT FK_DSCharacter_adventureId FOREIGN KEY (adventureId) REFERENCES Adventure (id)
ALTER TABLE User ADD CONSTRAINT FK_User_roleId FOREIGN KEY (roleId) REFERENCES AccessRole (id)
ALTER TABLE User ADD CONSTRAINT FK_User_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE Skill ADD CONSTRAINT FK_Skill_keyAbilityId FOREIGN KEY (keyAbilityId) REFERENCES Ability (id)
ALTER TABLE Message ADD CONSTRAINT FK_Message_adventureId FOREIGN KEY (adventureId) REFERENCES Adventure (id)
ALTER TABLE Message ADD CONSTRAINT FK_Message_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE DeityDomain ADD CONSTRAINT FK_DeityDomain_domainId FOREIGN KEY (domainId) REFERENCES DivineDomain (id)
ALTER TABLE DeityDomain ADD CONSTRAINT FK_DeityDomain_deityId FOREIGN KEY (deityId) REFERENCES Deity (id)
ALTER TABLE ClassSavingThrowProficiencies ADD CONSTRAINT FK_ClassSavingThrowProficiencies_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassSavingThrowProficiencies ADD CONSTRAINT FK_ClassSavingThrowProficiencies_abilityId FOREIGN KEY (abilityId) REFERENCES Ability (id)
ALTER TABLE ClassArmorProficiencies ADD CONSTRAINT FK_ClassArmorProficiencies_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassWeaponProficiencies ADD CONSTRAINT FK_ClassWeaponProficiencies_weaponTypeId FOREIGN KEY (weaponTypeId) REFERENCES WeaponType (id)
ALTER TABLE ClassWeaponProficiencies ADD CONSTRAINT FK_ClassWeaponProficiencies_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassSpell ADD CONSTRAINT FK_ClassSpell_classId FOREIGN KEY (classId) REFERENCES Class (id)
ALTER TABLE ClassSpell ADD CONSTRAINT FK_ClassSpell_spellId FOREIGN KEY (spellId) REFERENCES Spell (id)
ALTER TABLE CharacterFeat ADD CONSTRAINT FK_CharacterFeat_featId FOREIGN KEY (featId) REFERENCES Feat (id)
ALTER TABLE CharacterFeat ADD CONSTRAINT FK_CharacterFeat_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE BackgroundSkillProficiencies ADD CONSTRAINT FK_BackgroundSkillProficiencies_skillId FOREIGN KEY (skillId) REFERENCES Skill (id)
ALTER TABLE BackgroundSkillProficiencies ADD CONSTRAINT FK_BackgroundSkillProficiencies_backgroundId FOREIGN KEY (backgroundId) REFERENCES Background (id)
ALTER TABLE BackgroundToolProficiencies ADD CONSTRAINT FK_BackgroundToolProficiencies_backgroundId FOREIGN KEY (backgroundId) REFERENCES Background (id)
ALTER TABLE SpellComponentType ADD CONSTRAINT FK_SpellComponentType_spellId FOREIGN KEY (spellId) REFERENCES Spell (id)
ALTER TABLE SpellComponent ADD CONSTRAINT FK_SpellComponent_equipmentId FOREIGN KEY (equipmentId) REFERENCES Equipment (id)
ALTER TABLE SpellComponent ADD CONSTRAINT FK_SpellComponent_spellId FOREIGN KEY (spellId) REFERENCES Spell (id)
ALTER TABLE RaceLanguage ADD CONSTRAINT FK_RaceLanguage_languageId FOREIGN KEY (languageId) REFERENCES Language (id)
ALTER TABLE RaceLanguage ADD CONSTRAINT FK_RaceLanguage_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE RaceSavingThrowProficiencies ADD CONSTRAINT FK_RaceSavingThrowProficiencies_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE RaceArmorProficiencies ADD CONSTRAINT FK_RaceArmorProficiencies_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE RaceWeaponProficiencies ADD CONSTRAINT FK_RaceWeaponProficiencies_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE RaceWeaponProficiencies ADD CONSTRAINT FK_RaceWeaponProficiencies_weaponTypeId FOREIGN KEY (weaponTypeId) REFERENCES WeaponType (id)
ALTER TABLE RaceSkillProficiencies ADD CONSTRAINT FK_RaceSkillProficiencies_skillId FOREIGN KEY (skillId) REFERENCES Skill (id)
ALTER TABLE RaceSkillProficiencies ADD CONSTRAINT FK_RaceSkillProficiencies_raceId FOREIGN KEY (raceId) REFERENCES Race (id)
ALTER TABLE CharacterProficientSkill ADD CONSTRAINT FK_CharacterProficientSkill_characterId FOREIGN KEY (characterId) REFERENCES DSCharacter (id)
ALTER TABLE CharacterProficientSkill ADD CONSTRAINT FK_CharacterProficientSkill_skillId FOREIGN KEY (skillId) REFERENCES Skill (id)
